# Generated by Django 4.1.7 on 2023-03-09 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_user', models.CharField(max_length=20)),
                ('emp_pass', models.CharField(max_length=20)),
                ('emp_fname', models.CharField(max_length=20)),
                ('emp_lname', models.CharField(max_length=20)),
                ('emp_sex', models.CharField(max_length=1)),
            ],
        ),
    ]
